name: 🐞 버그 제보
title: "fix: "
description: BeerMap 서비스를 개선하는 데 도움을 주는 버그 신고서를 작성합니다.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: 버그 신고서를 작성해 주셔서 감사합니다!

  - type: textarea
    attributes:
      label: 에러에 대한 간단한 설명
    validations:
      required: true

  - type: textarea
    attributes:
      label: 비디오 또는 스크린샷
      description: 좋은 정보를 제공해주시면 더 빠르게 만들 수 있습니다!
    validations:
      required: false

  - type: textarea
    attributes:
      label: 기대되는 동작
      description: 예상한 동작에 대한 간단한 설명
    validations:
      required: false

  - type: textarea
    attributes:
      label: 에러 재현 방법
      description: 구체적일수록 빠르게 수정할 수 있습니다.
      placeholder: |
        나는 이런 쿼리를 사용했고...
        BeerMap을 실행 중이었으며...
        이 에러가 발생했습니다...
    validations:
      required: false

  - type: textarea
    attributes:
      label: 그 외 의견
      description: |
        링크, 참조, 의견 등을 남겨주시면 감사합니다!
    validations:
      required: false
